export const ENV = {
  DATABASE_URL: process.env.DATABASE_URL,
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

  NAVER_CLIENT_ID: process.env.NAVER_CLIENT_ID,
  NAVER_CLIENT_SECRET: process.env.NAVER_CLIENT_SECRET,

  KAKAO_CLIENT_ID: process.env.KAKAO_CLIENT_ID,
  KAKAO_CLIENT_SECRET: process.env.KAKAO_CLIENT_SECRET,

  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,

  OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY,

  SENTRY_DSN: process.env.SENTRY_DSN
};
