import type { Metadata } from 'next';

import './global-style.css';
import { RQProvider } from '@/provider/react-query-provider';
import Header from '@/features/layout/header';
import AuthProvider from '@/provider/auth-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <AuthProvider>
          <RQProvider>
            <Header />
            {children}
          </RQProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
