import AuthProvider from '@/provider/auth-provider';
import { RQProvider } from '@/provider/react-query-provider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './global-style.css';

const suit = localFont({
  src: '../../public/fonts/SUIT-Variable.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ko'>
      <body>
        <AuthProvider>
          <RQProvider>
            <div className={suit.className}>{children}</div>
          </RQProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
